theme:
  name: "material"
  custom_dir: overrides
  language: zh
  features:
    - navigation.instant
  favicon: assets/images/favicon.ico
  icon:
    logo: material/book
site_name: 郭睿明的小屋
site_url: http://guoruiming.com
markdown_extensions:
  - admonition
  - nl2br
  - pymdownx.arithmatex:
      generic: true
  - pymdownx.magiclink
  - pymdownx.highlight:
      use_pygments: false
  # - codehilite:
  #     guess_lang: false
  #     linenums: true
  - toc:
      permalink: true
  - footnotes
  - meta
  - def_list
  # - pymdownx.betterem:
  #     smart_enable: all
  - pymdownx.caret
  - pymdownx.critic
  - pymdownx.details
  - pymdownx.emoji:
      emoji_generator: !!python/name:pymdownx.emoji.to_png
        # emoji_generator: !!python/name:pymdownx.emoji.to_svg
        # emoji_generator: !!python/name:pymdownx.emoji.to_png_sprite
        # emoji_generator: !!python/name:pymdownx.emoji.to_svg_sprite
        # emoji_generator: !!python/name:pymdownx.emoji.to_awesome
        # emoji_generator: !!python/name:pymdownx.emoji.to_alt


  - pymdownx.inlinehilite
  - pymdownx.mark
  - pymdownx.smartsymbols
  - pymdownx.tasklist
  - pymdownx.tilde
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format

repo_url: https://gitee.com/dandelight/blog
repo_name: dandelight/blog

plugins:
  - search
  # - mermaid2
  - git-revision-date
  - callouts
  # feature of callouts plugin is covered by obsidian-support plugin
  # but it is unstable
  # - obsidian-support

extra_css:
  - https://cdn.jsdelivr.net/gh/highlightjs/cdn-release/build/styles/default.min.css
  - assets/stylesheets/extra.css
extra_javascript:
  - https://polyfill.io/v3/polyfill.min.js?features=es6
  - assets/javascripts/config.js
  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js
  # - https://cdn.jsdelivr.net/npm/mermaid/dist/mermaid.min.js # Use built-in mermaid plugin
  - https://cdn.jsdelivr.net/npm/@highlightjs/cdn-assets@11.3.1/highlight.min.js

copyright: 'Copyleft. All wrongs reversed.<br/><a href="https://beian.miit.gov.cn">冀ICP备2021025718号</a> | <a href="http://www.beian.gov.cn/">川公安网备51012202001103号</a>'
